site_name: robodev
site_url: https://robodev8g.github.io/ # must have the trailing slash
nav:
  - Home: index.md
  - ROS2:
    - Setup: ros/setup.md
    - Create Worksapce: ros/ros_fundementals.md
    
theme:
  name: lumen
  # favicon: favicon.ico
  # features:
  # - content.code.copy
  # - content.code.select
  # - content.code.annotate

# markdown_extensions:
#   - attr_list # allow to add HTML attributes and CSS classes
#   - md_in_html # allow to write Markdown inside HTML elements
#   - pymdownx.highlight:
#       anchor_linenums: true
#       line_spans: __span
#       pygments_lang_class: true
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - pymdownx.superfences